packages:
  - 'packages/browser/*'
  - 'packages/shared/*'
  - 'packages/server/*'
  - 'packages/universal/*'
  - 'apps/browser/*'
  - 'apps/server/*'

catalog:
  '@types/node': 24.3.0
  '@types/aws-lambda': 8.10.152
  typescript: 5.9.2
  eslint: 9.33.0
  esbuild: 0.25.9
  tsx: 4.20.5
