packages:
  - services/*
  - packages/browser/*
  - packages/server/*
  - packages/workspace/*

# Global catalog
catalog:
  typescript: ">=5.7"

nodeVersion: 24.0.2 
engineStrict: true
strictPeerDependencies: true
packageManagerStrictVersion: true
savePrefix: ""

nodeOptions: "--no-warnings=ExperimentalWarning"