name: Lint Codebase

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: package.json

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --dev

      - name: Perform linting
        run: pnpm lint -- --exit-on-fatal-error 