name: Release

on:
  push:
    branches:
      - main

env:
  DO_NOT_TRACK: 1
  HUSKY: 0

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.repository == 'stefan-karlsson/aviene'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Creates pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update package versions"
          title: "chore: update package versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        run: echo "A new version of ${GITHUB_REPOSITORY} was published!"
